- name: tag demo on tasks
  hosts: localhost
  tasks:
    - name: Catalogue
      debug:
        msg: Hello from catalogue
      tags: catalogue
    - name: Frontend
      debug:
        msg: Hello from frontend
      tags: frontend
    - name: common
      debug:
        msg: Hello from common

## command to run "ansible-playbook 04-tags.yml -t frontend"

- name: demo of tag on play level
  tags: frontend
  hosts: localhost
  tasks:
    - name: frontend
      debug:
        msg: Hello from frontend
      tags: catalogue
