- name: tag demo on tasks
  hosts: localhost
  tasks:
    - name: Catalogue
      debug:
        msg: Hello from catalogue
      tags: catalogue
    - name: Frontend
      debug:
        msg: Hello from frontend
      tags: frontend
    - name: common
      debug:
        msg: Hello from common



## command to run "ansible-playbook 04-tags.yml -t frontend"