- name: tag demo on tasks
  hosts: localhost
  tasks:
    - name: Catalogue
      debug:
        msg: Hello from catalogue
      tags: catalogue
    - name: Frontend
      debug:
        msg: Hello from frontend
      tags: frontend
