- name: Demo on conditions
  hosts: localhost
  vars:
    abc: ABC
  tasks:
    - name: Condition with string
      debug:
        msg: "abc var = ABC"
      when: abc == "ABC"
    - name: Condition with string
      debug:
        msg: "abc var = abc"
      when: abc == "abc"
