- name: Demo on conditions
  hosts: localhost
  vars:
    abc: ABC
    val: 100
  tasks:
    - name: Condition with string
      debug:
        msg: "abc var = ABC"
      when: abc == "ABC"

    - name: Condition with string
      debug:
        msg: "abc var = abc"
      when: abc == "abc"

    - name: Condition with number
      debug:
        msg: "val var is less then 100"
      when: val | int < 100

    - name: Condition with number
      debug:
        msg: "val var is greater then or equal to 100"
      when: val | int >= 100

    - name: Run on boolean
      debug:
        msg: "applying"
      when: applu
