- name: Demo on conditions
  hosts: localhost
  vars:
    abc: ABC
    val: 50
    apply: true
  tasks:
    - name: Condition with string
      debug:
        msg: "abc var = ABC"
      when: abc == "ABC"

    - name: Condition with string
      debug:
        msg: "abc var = abc"
      when: abc == "abc"

    - name: Condition with number
      debug:
        msg: "val var is less then 100"
      when: val | int < 100

    - name: Condition with number
      debug:
        msg: "val var is greater then or equal to 100"
      when: val | int >= 100

    - name: Run on boolean
      debug:
        msg: "applying"
      when: apply | bool
# apply - will run if apply is true
# not apply - will run if apply is false


## multiple conditions are possible, and - both conditions are true , or - any condition is true


    - name: multi condition
      debug:
        msg: val of abc = ABC and val of val is 50
      when: abc == "ABC" and val == 50