
## command to run: ansible-playbook 07-loops.yml

- name: Demo on loop
  hosts: localhost
  vars:
    FRUITS: [ "banana", "apple", "orange" ]
  tasks:
    - name: Print Fruit name
      loop: "{{FRUITS}}"
      debug:
        msg: "{{item}}"