- name: Add application user
  ansible.builtin.user:
    name: roboshop
    register: app_user_info


- name: Download and unzip {{COMPONENT}} Content
  ansible.builtin.import_role:
    name: common
    tasks_from: download


- name: Remove old Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy the App content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop