- name: Setup Nodejs Repo
  shell : curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJs service
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
      - npm
    state: installed

- name: Application user setup and download app files
  import_tasks: app-user-setup.yml

- name: Install Nodejs Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Setup service and start service
  import_tasks: systemd.yml






