groups:
  - name: Instance Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          type: instanceAlert
          kind: instanceDown
        annotations:
          summary: {%raw%}"Instance Down - IP - [{{ $labels.instance}}], Name[{{ $labels.instanceName}}]"{%endraw%}
          description: {%raw%}"Instance Down - IP - [{{ $labels.instance}}], Name[{{ $labels.instanceName}}]"{%endraw%}
      - alert: CpuUsage Alert
        expr: cpuUsagePercentage > 80
        for: 2m
        labels:
          severity: critical
          type: instanceAlert
          kind: cpuUsage
        annotations:
          summary: {%raw%}"CPU Usage - IP - [{{ $labels.instance}}], Name[{{ $labels.instanceName}}]"{%endraw%}
          description: {%raw%}"CPU Usage - IP - [{{ $labels.instance}}], Name[{{ $labels.instanceName}}]"{%endraw%}
      - alert: MemoryUsage Alert
        expr: memoryUsagePercentage > 80
        for: 2m
        labels:
          severity: critical
          type: instanceAlert
          kind: memoryHighUsage
        annotations:
          summary: {%raw%}"Memory High Usage - IP - [{{ $labels.instance}}], Name[{{ $labels.instanceName}}]"{%endraw%}
          description: {%raw%}"Memory High Usage - IP - [{{ $labels.instance}}], Name[{{ $labels.instanceName}}]"{%endraw%}